### PR TITLE
SQL Import Fix.

### PR DESCRIPTION
**Pull request by bruhmoment0lol**
Replaced utf8mb4_0900_ai_ci with utf8mb4_general_ci to fix potential issues with SQL importing.

### CODE REVIEW

**Comment by erievs** [comment]
Hey, I would appreciate it if you'd at least rebrand your Loogle+ instance to anything besides Loogle Plus. I would prefer you to shut it down, but I cannot stop you from making your own instance, as it is open source and under the GPL v2.0 license. Public instances are a pain in the ass for me to deal with at the moment, and since you are using loogleplus.xyz it is even more of a pain in the ass to deal with.

**Comment by erievs** [comment]
Can you explain to me why this is an issue?

**Comment by bruhmoment0lol** [comment]
1. I don't plan on keeping my instance up much longer anyway. Hell, I'll give you the domain if you want.
2. When I tried importing the SQL, MySQL said utf8mb4_0900_ai_ci was an unknown collation, and when looking up a fix, replacing it with utf8mb4_general_ci fixed it.
EDIT: I shut it down, again, domains up for grabs if ya'd like :)

**Comment by bruhmoment0lol** [comment]
I really do admire your work on reviving Google+ btw. I am sorry to have caused an inconvenience.

**Comment by erievs** [comment]
Thank you! I mean, if you really wanted to fork loogle, you could always rebrand it. I was just a little mad because it was like 3am, and you used loogleplus branding. I think I overreacted a little bit.

**Comment by bruhmoment0lol** [comment]
It's fine. We all have days like that.

**Pull request merged**
